Presets:
  0:
    Liver failure:
      cui: 59927004
      ontologies: SNOMED CT
    Paracetamol:
      cui: 90332006
      ontologies: FDB
      dosage:
        dose:
          value: 500
          unit: mg
        duration:
          low: 20220606
          high: 20220620
        frequency:
          value: 0.25
          unit: d
        route:
          code: C38288
          displayName: Oral
    Penicillins:
      cui: 84874
      ontologies: ELG
      reaction:
        cui: 74474003
        name: Gastrointestinal bleeding
        ontologies: SNOMED CT
      severity:
        cui: M
        name: Moderate
        ontologies: ActCode

CDA:
  0:
    Problems:
      # whether problem is an active concern to clinician
      statusCode: active
      # time when the problem stop become a concern to clinician -  there will always be a low (implicit)
      actEffectiveTimeHigh: None
      # problem onset - can be a date in the past
      observationEffectiveTimeLow: 20200504
      # problem resolve date
      observationEffectiveTimeHigh: 20210904
    Medication:
      # the code system name for medication and template id to send back to the CDA
      consumableCodeSystemName: RxNorm
      consumableCodeSystemValue: 2.16.840.1.113883.6.88
    Allergy:
      # the allergy section code to send back - either propensity to adverse reaction or allergy to substance
      allergySectionCodeName: Allergy to substance
      allergySectionCodeValue: 419199007

# model options - to be developed
Model:
  modelId: 0