models:
  problems: f25ec9423958e8d6
  meds/allergies: a146c741501cf1f7
annotators:
  problems: ProblemsAnnotator
  meds/allergies: MedsAllergiesAnnotator
general:
  problems:
    lookup_data_path: ./lookup_data/
    negation_detection: None
    disable: []
  meds/allergies:
    lookup_data_path: ./lookup_data/
    negation_detection: None
    disable: []