snomed_data_path: data/snomed/SnomedCT_UKEditionRF2_PRODUCTION_20220413T000001Z
#fdb_data_path: ./data/fdb/exports/drug_names_export.csv
#elg_data_path: ./data/allergens/ELG_ALLERGEN.csv
snomed_exclusions_path: ./data/snomed/exclude_concepts.txt
training_data_path: ./tests/examples/wikipedia_sample.txt
output_dir: ./dev_models/modelpack
